### ISSUE TITLE
[Clarification/Feedback] Total Sales from Revenue

### ISSUE THREAD

**Issue by bcyee1** [sigmacomputing/sigmaquickstarts#107]
![Screenshot 2023-07-18 at 9 54 28 AM](https://github.com/sigmacomputing/sigmaquickstarts/assets/139162552/0333cc52-d421-4a3b-bb42-d1075d813b2d)

When it mentions `Total Sales` for a person following along from `Fundamentals 2.4` the column that we're looking for is `Revenue` as the source column so that a person matches the value in the screenshot and therefore feels assured that they are following along correctly.

## Recommended Action
Change

> From there you can `rename the Value column` from Revenue to `Total Sales` and `format` the value to currency and truncate the trailing decimals.

To
> From there you want to add `Revenue` to the Value. It will automatically be named "Sum of Revenue", but we can rename it `Total Sales` instead.  If the data is not formatted to currency you can easily change that and truncate the trailing decimals for a cleaner look.

**Comment by pballai** [comment]
This change is made and will be in production later today.
