### ISSUE TITLE
[Bug] Using a direct link breaks the ability to quickly navigate to other QuickStart topics

### ISSUE THREAD

**Issue by bcyee1** [sigmacomputing/sigmaquickstarts#109]
## Repro Steps
1. Go to: https://help.sigmacomputing.com/hc/en-us/articles/16536923653139-Sigma-QuickStarts
2. Click _any_ of the topics, which opens in a new tab by default
3. Under the search bar select a _different_ topic (administration, embedding, functions, fundamentals, partners, snowflake, tables, use cases)

## Expected Results
Clicking on a different topic ought to load the articles/activities for that new topic

## Actual Results
No articles/activities load when clicking other topics

![2023-07-20 09 53 54](https://github.com/sigmacomputing/sigmaquickstarts/assets/139162552/34fa6f3d-b522-4a35-8e41-51e6cc08c6d5)

## Notes
https://www.whatsmybrowser.org/b/7430S

**Comment by pballai** [comment]
I have informed the doc team to take a look at these links. Will leave this issue open till it is resolved or the pages are replaced with QuickStarts.

**Comment by pballai** [comment]
This seems stalled. Opened a JIRA:
https://sigmacomputing.atlassian.net/browse/DOCS-2018
