### ISSUE TITLE
Embedding 5 - Feedback

### ISSUE THREAD

**Issue by bcyee1** [sigmacomputing/sigmaquickstarts#140]
TL;DR - make some mention that the Salesforce Account Email need to exist both in Salesforce and in Sigma

User was following along in: https://quickstarts.sigmacomputing.com/guide/embedding_5_application_embedding_into_salesforce/index.html?index=..%2F..index#1

They got to Step 2: `SigmaEmbedClass`
They updated the script with their values, however
> understanding this error on embedded workbook.
> You don't have permission to access this page. ":email" matches internal user. Cannot login as internal user through embed parameter

Went back and forth with them for a bit, but eventually they figured out before I could get back to them
> That scripts generates an embed user from a salesforce account email. I had to go add that ghost user to a team, and it all started working

**Comment by pballai** [comment]
Added additional text to help users avid this issue in the relevant section. Thanks for reporting it!
