### ISSUE TITLE
Small typo in quickstart

### ISSUE THREAD

**Issue by jbruneFei** [sigmacomputing/sigmaquickstarts#223]
1. https://quickstarts.sigmacomputing.com/guide/embedding_03_secure_access/index.html?index=..%2F..index#0
> Secure embedding is by far the most popular method Sigma **customer** use, as it **works the** Parent application's authentication, to pass user-level permissions and more at runtime.

2. https://quickstarts.sigmacomputing.com/guide/embedding_03_secure_access/index.html?index=..%2F..index#2
![image](https://github.com/sigmacomputing/sigmaquickstarts/assets/40606750/7ba513e8-af87-4082-b0ca-01919c9d6319)
The link for User Account Types takes you to a page that says there are 4 default user account types: Lite/Essential/Pro/Admin.  
But further down is says,
![image](https://github.com/sigmacomputing/sigmaquickstarts/assets/40606750/b59e0b84-9a1f-4df7-b5f0-d41496a018dc)
Are there 4 user account types, or 2?

(fyi, I'm really liking these quick starts.  They're very useful.)

**Comment by pballai** [comment]
Thank you for the kind feeback. We have migrated from the older account types to ones that match our licensing plans (Lite, Essential, Pro. The QuickStart will be updated later today to reflect this.
