### ISSUE TITLE
Embedding 10: Responsive Embeds Dead Link

### ISSUE THREAD

**Issue by bombledmonk** [sigmacomputing/sigmaquickstarts#224]
On the following page the screen https://quickstarts.sigmacomputing.com/guide/embedding_10_responsive_embeds/#0 the screnshotted link 404s. 
![image](https://github.com/sigmacomputing/sigmaquickstarts/assets/4141691/1283ee63-4465-4d91-bc80-ff8efae55615)

**Comment by pballai** [comment]
Corrected. Thanks for reporting the issue.
