### ISSUE TITLE
Typo That Could Benefit From Rephrasing

### ISSUE THREAD

**Issue by Ho1yShif** [sigmacomputing/sigmaquickstarts#228]
In this [quickstart](https://quickstarts.sigmacomputing.com/guide/fundamentals-1-getting-around/index.html?index=..%2F..index#7), you say `For Workbooks that have parameter driven data based on the user, you sent items can be run with data filtered for the recipient.`.

It should be `For Workbooks that have parameter driven data based on the user, youR sent items can be run with data filtered for the recipient.`

I think this could also be better phrased as `If your workbook contains parameter-driven data based on the user, sent items will use filtered data based on the recipient`.

Thanks!

**Comment by pballai** [comment]
Corrected. Thanks for reporting the issue.
