### ISSUE TITLE
Quickstart: Run-on Sentence

### ISSUE THREAD

**Issue by Ho1yShif** [sigmacomputing/sigmaquickstarts#234]
The last sentence in this [quickstart](https://quickstarts.sigmacomputing.com/guide/retail-cpg-2-cohort-analysis/index.html?index=..%2F..index#1) currently says: `This will pop out the formatting pane on the left side of the screen, select the "DATA BARS" tab strip to apply them to the column.`
It should be broken up: `This will pop out the formatting pane on the left side of the screen. Then, select the "DATA BARS" tab strip to apply them to the column.`

**Comment by pballai** [comment]
This is fixed.
