### ISSUE TITLE
Link to old reference site

### ISSUE THREAD

**Issue by ColinGreybosh** [sigmacomputing/sigmaquickstarts#251]
Located at: https://quickstarts.sigmacomputing.com/guide/administration_api_code_samples/index.html?_gl=1*1qlr87k*_gcl_au*OTk4MzA4NDAxLjE3MTM1NTA5Njg.*_ga*MTQyMjgxMTk2MS4xNzA1NDQ3NjAx*_ga_PMMQG4DCHC*MTcyMDIxODA4OS4yMDYuMS4xNzIwMjE5MzY4LjU0LjAuMA..#2

The "located here" link in the introduction points to the old API reference site:
> This section demonstrates the code that was provided on the API Code Samples > Authentication: Get Access Token page, [located here.](https://docs.sigmacomputing.com/api/v2/#auth)

**Comment by pballai** [comment]
This has been corrected. Thanks for reporting it Colin.
