### ISSUE TITLE
supervisor install doesn't work on mac

### ISSUE THREAD

**Issue by TomOrthCellEd** [sigmacomputing/sigmaquickstarts#253]
supervisor installs without errors, but the command isn't recognized. Chat with support is here: https://app.intercom.com/a/inbox/gu1e0q0t/inbox/admin/7432651/conversation/105211900916532?view=TableFullscreen

I ultimately did an npm install -g supervisor and then the command was recognized.

Using a mac with bash running on bare metal (no vm).

**Comment by pballai** [comment]
Hi TomOrthCellEd,
My name is Phil and I write QuickStart for Sigma. I am aware of this issue with installing node packages and permissions on various O/S and O/S versions. While I am considering alternatives for supervisor, the supervisor package is not a Sigma requirement. It is only a convienence to save the user time after editing/saving the project files. I am not trying to make an excuse but rather just explaining the "why". That said, if you want to have a zoom meeting on your issue and anything else you need, I am open to that. Feel free to contact me at phil@sigmacomputing.com and I will reach out with a meeting.

Thank you,
Phil

**Comment by pballai** [comment]
I have updated the first embed QuickStart, adding a section to discuss "module not found" issues. I hope this helps.

Scroll to the bottom of the page:
https://quickstarts.sigmacomputing.com/guide/embedding_01_prerequisites/index.html?index=..%2F..index#2

**Comment by TomOrthCellEd** [comment]
I would also add a section for what to do if you choose not to use the
supervisor. Saying it is optional - but not describing what to do if you
don't use it, is a bit confusing. Unless you state up front that a working
familiarity with Node.js is required for this tutorial.

**Comment by pballai** [comment]
I understand your point and will add that information too.

**Comment by pballai** [comment]
I have added a some additional information as you requested. Thanks for sharing your thoughts to make this as clear as possible.
