### ISSUE TITLE
Missing "Brand" field in "Fundamentals 2: Working with Tables v2"

### ISSUE THREAD

**Issue by nhitt0716** [sigmacomputing/sigmaquickstarts#280]
It appears that the Fundamentals 2: Working with Tables v2 self-paced tutorial shows a different field than what is available in the dataset-- "Brand."
The tutorial shows "Brand" as a column/field name but the dataset does not have Brand.

**Comment by pballai** [comment]
Hi Nick, 
Is it possible that you are using a different table than what was called for? The table 
RETAIL / PLUGS_ELECTRONICS / PLUGS_ELECTRONICS_HANDS_ON_LAB_DATA
has a brand column and is the table to use.

**Comment by pballai** [comment]
No problem Nick. Glad you solved it. You can also use the "?" icon in Sigma to get real time chat help (with a human!). We pride on support. 
Enjoy QuickStarts.
PhilB

**Comment by pballai** [comment]
Closing issue.
