### ISSUE TITLE
URLL -> URL

### ISSUE THREAD

**Issue by Ho1yShif** [sigmacomputing/sigmaquickstarts#289]
Hi Phil,
The base URL environment variable (in both the code files and the [quickstarts](https://quickstarts.sigmacomputing.com/guide/embedding_16_jwt/index.html?index=..%2F..index#4)) is incorrectly called `BASE_URLL` instead of `BASE_URL`. My JWT embed didn't load until I made this correction
[See image here](https://quickstarts.sigmacomputing.com/guide/embedding_16_jwt/img/28ba0764343c505c.png)

**Comment by pballai** [comment]
Not really sure how this one snuck in and got past me but I fixed the screenshot in the QuickStart and the .env file in the git repo. Sorry for the delay; I was on vacation. Thanks for reporting it.
