### ISSUE TITLE
Errors in Screenshots

### ISSUE THREAD

**Issue by ryan-sigmacomputing** [sigmacomputing/sigmaquickstarts#298]
<img width="744" alt="Screenshot 2024-10-28 at 11 10 01 AM" src="https://github.com/user-attachments/assets/9528529b-a2a0-4262-ad40-ed1e4ffac25d">

The screenshot shows 2 different implementations of the Rank function, which is vital to success of the calculation.

**Comment by pballai** [comment]
Which QuickStart Ryan? Thanks
