### ISSUE TITLE
Incorrect Subtotal "Mode"

### ISSUE THREAD

**Issue by ryan-sigmacomputing** [sigmacomputing/sigmaquickstarts#299]
Syntax technically works, but is incorrect per the Sigma help documentation

<img width="732" alt="Screenshot 2024-10-28 at 11 10 52 AM" src="https://github.com/user-attachments/assets/77a208d9-bc73-4035-8274-bac31e2bbc23">
source: https://quickstarts.sigmacomputing.com/guide/use_cases_finance_discounted_cash_flow/index.html?index=..%2F..index#1

______________________

<img width="627" alt="Screenshot 2024-10-28 at 11 11 11 AM" src="https://github.com/user-attachments/assets/d3d621aa-126e-4b42-9bf1-40d3ac96ec74">
source: https://help.sigmacomputing.com/docs/subtotal

**Comment by pballai** [comment]
Not sure what you are telling me Ryan. Can you ping me on slack as I am not sure which "Ryan" you are? Thanks.
