### ISSUE TITLE
Architecture Diagram for JWT authentication

### ISSUE THREAD

**Issue by guyathomas** [sigmacomputing/sigmaquickstarts#316]
The "Step-by-Step JWT Flow" could do with a system architecture / data flow diagram.

https://quickstarts.sigmacomputing.com/guide/embedding_16_jwt/index.html?index=..%2F..index#1

**Comment by pballai** [comment]
Hi guyathomas. There is a diagram on the Sigma help page under authentication flow here:
https://help.sigmacomputing.com/docs/create-an-embed-api-with-json-web-tokens#jwt-claims

Let me know if that suffices. If so, I can add it to the QuickStart as well. 
Thanks for the feedback.

**Comment by pballai** [comment]
Reopen if more questions.
