### ISSUE TITLE
Dead link on Fundamentals 2: Working with Tables v2

### ISSUE THREAD

**Issue by wkaufman-whoop** [sigmacomputing/sigmaquickstarts#320]
The following link 404s:

> If you are really interested in the low-level workings of Sigma's unique approach to data retrieval, read [this QuickStart.](https://quickstarts.sigmacomputing.com/guide/administration_sigma_calculations/index.html?index=..%2F..index#0)

Thanks for updating with the correct documentation!

**Comment by pballai** [comment]
This is corrected. Thank you for reporting it.
