### ISSUE TITLE
Missing column in step 8 of date quickstart

### ISSUE THREAD

**Issue by br524** [sigmacomputing/sigmaquickstarts#43]
On this page: https://quickstarts.sigmacomputing.com/guide/common_date_functions_and_use_cases/index.html?index=..%2F..index#8, it says: "On the second table, hide all the columns leaving only Store Name, Store Region, Store Key and Quantity."

Add "Date" to this list, as it is used just two steps later.

**Comment by pballai** [comment]
fixed and waiting on approval to push

**Comment by pballai** [comment]
Fixed.
