### ISSUE TITLE
Fundamentals 3 gives conflicting dependency information

### ISSUE THREAD

**Issue by robarnold** [sigmacomputing/sigmaquickstarts#76]
On the first page it says:
> The other "Fundamental Series" QuickStarts explore topics such as working with Tables, Pivot Tables, Dashboards and more. We have broken these QuickStarts up so that they can be taken in any order you want, except the "Fundamentals 1: Getting Around" QuickStart should be taken first.

But on the second page it says:
> Our starting point is the "Plugs Sales" Workbook created in the "Fundamentals 2: Working with Tables" QuickStart.

The screenshots show the columns added in Fundamentals 2 and the text references them as well (ex: `[Profit]`).

**Comment by pballai** [comment]
Adjusted text to "This QuickStart assumes you have already taken the Fundamentals 1 & 2 QuickStarts "
