### ISSUE TITLE
Input Tables Tutorial Step 3 setup is confusing

### ISSUE THREAD

**Issue by robarnold** [sigmacomputing/sigmaquickstarts#77]
I don't know where to get the Brick & Mortar data from. I think it wants me to use the plugs labs data, but the instructions are to add that to a new page named "data" rather than the first page. Then in the screenshot after that, both tables are on the same page and the page title doesn't match the one in the tutorial.

**Comment by pballai** [comment]
This is corrected with multiple changes to section to add clarity and fix incorrect workflow.
